[project]
name = "backened"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "pandas>=2.3.0",
    "streamlit>=1.45.1",
    "uvicorn[standard]>=0.34.3",
]
